### ISSUE TITLE
labels.txt

### ISSUE THREAD

**Issue by lbarqueira** [kshitizrimal/Classification-Flutter-TFlite#1]
Important to notice that the link you provide at your youtube presentation "On-Device Machine Learning with Flutter - Kshitiz Rimal (Flutter Week)", to get the labels.txt, more exactly https://github.com/leferrad/tensorflow-mobilenet/blob/master/imagenet/labels.txt does not work with the mobilenet.tflite of this repo. The app crashes. The labels.txt to use is the one presented in this repo.

**Comment by kshitizrimal** [comment]
I see, thank you.  The only difference here is that, I have removed the "background" label from the labels.txt file. If you use the labels.txt from the given repo and remove the background label, it should work.
